### ISSUE TITLE
Implementar o Padrão de Projeto Adapter

### ISSUE THREAD

**Issue by DanielSuzuki1** [XBrunoGomesX/padroes-de-projeto#11]
O padrão de projeto Adapter é utilizado para permitir que interfaces incompatíveis trabalhem juntas. Ele atua como um "adaptador" entre duas interfaces, permitindo que uma classe se comunique com outra, mesmo que suas interfaces sejam diferentes.

A descrição é que atualmente, temos duas APIs no sistema que têm interfaces incompatíveis, o que dificulta a comunicação entre elas. Para resolver esse problema, será necessário aplicar o Padrão de Projeto Adapter, que permitirá que uma interface seja adaptada para a outra, facilitando a integração.

O principal objetivo é Implementar um Adapter para permitir que a API A, que retorna dados em um formato JSON, seja consumida pela API B, que espera os dados no formato XML.

dentre as tarefas:
1.criar interface do adapter: Definir uma interface comum que será usada para a conversão entre os formatos de dados.
2.desenvolver o adapter: Criar uma classe AdapterAPI que implementa a interface criada. A classe deve ter métodos para converter JSON para XML e vice-versa, conforme a necessidade da integração.
3.integrar api a com api b, Ajustar a lógica de comunicação entre as duas APIs para usar o Adapter, sem a necessidade de mudanças nas APIs originais.
4.testar a integração, Garantir que os dados estão sendo convertidos corretamente entre os dois formatos. Validar a comunicação entre as APIs com testes automatizados.

**Comment by XBrunoGomesX** [comment]
Posso atribuir esse padrão?
