### ISSUE TITLE
Implementar o Padrão de Projeto Observer

### ISSUE THREAD

**Issue by JoaoP55** [XBrunoGomesX/padroes-de-projeto#2]
O observer é um padrão de design comportamental que permite definir um mecanismo de assinatura para notificar vários objetos sobre quaisquer eventos que aconteçam com o objeto que estão observando.

Exemplo: Imagine um Fornecedor de Notícias que envia atualizações para diferentes Assinantes (por email, SMS, etc.). Sempre que o fornecedor publica uma nova notícia, ele notifica automaticamente todos os seus assinantes, sem precisar saber como cada um processa a notícia.

**Comment by PedroBorges0** [comment]
Posso atribuir seu padrão?
