### ISSUE TITLE
Implementar o Padrão de Projeto Factory

### ISSUE THREAD

**Issue by PedroBorges0** [XBrunoGomesX/padroes-de-projeto#3]
Descrição: O Factory é um padrão criacional de projeto que fornece uma interface para criar objetos em uma superclasse, mas permite que as subclasses alterem o tipo de objetos que serão criados, utilizado para criar objetos sem expor a lógica de criação ao cliente e sem especificar a classe exata do objeto que será criado. A principal vantagem desse padrão é a flexibilidade e a manutenção do código.

Exemplo: Imagine que você está em uma fábrica de carros que tem diferentes modelos de carros disponíveis para os consumidores. Quando um cliente chega e pede um carro, ele não precisa saber como o carro é montado, quais peças específicas são utilizadas ou qual o processo de fabricação. O cliente apenas escolhe o tipo de carro que quer, e a fábrica cuida de toda a parte de construção do veículo.

**Comment by JoaoP55** [comment]
Posso atribuir esse padrão?
