### ISSUE TITLE
Implementar Padrão de Projeto Proxy

### ISSUE THREAD

**Issue by DanielSuzuki1** [XBrunoGomesX/padroes-de-projeto#4]
O padrão proxy oferece um representante ou substituto para outro objeto, esse outro objeto pode ser por exemplo uma classe, o padrão proxy ele pode ser útil quando se procura controlar o acesso a um objeto ou classe também chamado, ou, quando por exemplo é preciso criar e adicionar um comportamento extra para mas que não modifique o objeto original.
Existem diferentes tipos de proxys: proxy virtual, proxy remoto, proxy de proteção, dentre outros.

Exemplo de aplicação na prática do padrão proxy: para a implementação do proxy na prática, o proxy e o objeto real devem implementar a mesma interface, pois, isso garante que independentemente, de estarmos lidando com o proxy ou com o objeto real, o comportamento esperado será o mesmo.
Digamos que tenhamos um objeto que representa um documento e o proxy irá controlar o acesso ao carregamento desse documento
interface comum:
class Documento:
    def exibir_conteudo(self):
        pass
isso é apenas um exemplo ilustrativo depois seria necessário criar o objeto real

**Comment by XBrunoGomesX** [comment]
Posso atribuir esse padrão?
