### ISSUE TITLE
Implementar Padrão de Projeto Adapter

### ISSUE THREAD

**Issue by XBrunoGomesX** [XBrunoGomesX/padroes-de-projeto#6]
O padrão adapter é um padrão estrutural usado para permitir que duas interfaces incompatíveis trabalhem juntas. Ele age como um tradutor que converte a interface de uma classe em outra que o cliente espera, permitindo a integração entre componentes que, de outra forma, não seriam compatíveis.

**Comment by DanielSuzuki1** [comment]
Posso atribuir esse padrão?
